---
output-file: "thesis-index"
---

## Abstract {.unnumbered}

Forest managers practicing retention forestry in the west need data on
regeneration dynamics and hazardous fuels to design structures that are
productive and fire resilient. This analysis of the 10-year re-measure of the
redwood multi-aged experiment in the Jackson Demonstration State Forest in
Mendocino County, California, explores the regeneration response of several
species following different harvesting techniques including group selection
(GS), high-density aggregated retention (HA), and high/low density dispersed
retention (HD; LD). We measured size and growth of 10-year old redwood and
tanoak stump sprout regeneration, the density of all tree species, and surface
fuels 10 years after partial harvests.

Redwood regeneration responded strongly and positively to increasing openness
(10.1 m^2^ ha^-1^ in GS vs 0.9 m^2^ ha^-1^ in HD). Tanoak basal area response
was comparatively modest and was lowest in the HA treatment (2.2 m^2^ ha^-1^ in
GS vs 1.3 m^2^ ha^-1^ in HA). The difference between redwood and tanoak sprout
basal area decreased quickly with increasing canopy cover and tanoak basal area
was slightly greater than that of redwood in the HD treatment. Douglas-fir
seedling counts were consistent across treatments with an average expectation of
413 seedlings per hectare.

Redwood grew faster and achieved greater heights than tanoak across all
treatments and growth periods. But redwood height growth slowed more than tanoak
in years 5-10 compared to years 1-5 (0.8 m yr^-1^ -> 0.67 m yr^-1^ for redwood,
vs. 0.39 m yr^-1^ -> 0.34 m yr^-1^ for tanoak). The mean height of redwood
sprouts at Year 10 ranged from 10.64 m in the GS treatment to 6.3 m in the HD
treatment. For tanoak, predicted mean height ranged from 5.2 m (GS) to 3.08 m
(HD).

Fuel loading generally showed few statistically significant differences between
treatments. Vegetative fuel loading was highest in the GS treatment and nearly 3
times that of the HA treatment which was lowest. One-hour fuels were highest in
the HA treatment and around double that of the GS treatment.

The PCT dramatically reduced live surface fuels and increased fine dead surface
fuels including 10- and 100-hour fuels, leading to greater stratification of
treatments in terms of dead fuels.

Harvesting techniques designed to promote productivity (like GS, LD) resulted in
significantly greater redwood growth and height. However, these same
techniques also produced higher levels of live vegetation fuels pre-PCT and,
consequently, higher volumes of fine dead fuels (10-hr and 100-hr) immediately
following the PCT fuels treatment.


## Acknowledgements {.unnumbered}

I would like to thank my advisor Pascal Berrill for his long standing support
and unwavering flexibility in accommodating my not-always-most-direct path and
unfailing confidence in my abilities. I'm indebted to his long-time investment
in me through the sharing of his knowledge and experience and enriched by his
friendship. My other committee members, Jeffrey Kane, and Rosanna Overholser
have also offered their long-suffering support, and friendship and have been
invaluable resources and trusted sounding blocks as I have navigated this
process. Their direction, advice, and encouragement were instrumental in my
continued commitment to completing my thesis. This thesis would not have been
possible without the administrative support of Nona Mineva, Erin Kelly, and
Eric Riggs. My field data would have been measly at best were it not for the
dedicated efforts of our field crew: Alan Cooper, JD Wilder, Destiny Rivera,
Keith Shuttle, Aidan Jack Murphy, Ian Blundell, Hanna Upton, and Ally Medina.

I acknowledge that this research was conducted on the unceded territory of the
Northern Pomo tribes, the original stewards of these lands. I recognize and
deeply regret our failure to engage with the tribe during our fieldwork. This
omission carries significant implications for the responsible management of
these forest ecosystems, particularly regarding the health and development of
tanoak, a keystone species and a principal food source sustaining the Pomo
people since time immemorial. I understand the importance of incorporating
Indigenous knowledge into ecological research and management, and I sincerely
hope that future projects on these lands will be conducted in genuine and
collaborative partnership with Pomo tribal members. I believe their expertise is
essential to ensuring the respectful and sustainable stewardship of their
ancestral territory.

I would like to thank my children: Fox and Hazel, and my loving partner Megan
for their support and patience in allowing me the time and space to continue
working on this thesis even when it went on much longer than I had originally
anticipated and meant the sacrifice of some of our precious shared weekend time.
I'm deeply grateful for their willingness to prioritize my personal development
and their confidence in my eventual success.

