# Discussion

::: {.callout-caution}
TODO:

- Is the regularization imposed on our random effects for sites appropriate if
  the distribution of site effect is bi-modal because of north vs south facing
  aspects?
- Aspect is an important predictor that was not explicitly accounted for in our
  model, and may have led to inflated uncertainty 
- Cost of treatments
- 1-hr redwood fuels differed from other studies in that we implemented a cutoff
- Discuss the decision to allow surface fuels to extend to greater than 2 meters
- It may have been better to analyze sprout composition directly using the
  binned data for the smaller sprouts, rather than converting to basal area
  based on an assumed midpoint diameter.
- Discuss the decision to combine live and dead vegetation fuels
- Discuss the decision to combine herbaceous and woody vegetation fuels
- Discuss the decision to combine duff and litter
- Discuss the decision to use basal area for redwood and tanoak and counts for
  Douglas-fir
- Discuss the similarity between vegetation fuel difference post-PCT and
  vegetation fuel loading pre-PCT
- Discuss the significance of 1-hr fuel loading pre-PCT vs post-PCT
- Discuss the significance of 10-hr fuel loading pre-PCT vs post-PCT
- Discuss the significance of 100-hr fuel loading pre-PCT vs post-PCT
- Discuss the similarity between redwood or tanoak basal area and vegetation fuel loading
- Discuss the potential over-estimation of vegetation fuel loading

:::

## Regeneration

### Redwood and tanoak

Basal area was selected as the metric for quantifying redwood and tanoak
abundance because prolific sprout regeneration in both species was undergoing
self-thinning. In this context, basal area provided a more informative measure
than stem density, as it better captured treatment responses by reflecting the
relative contribution of established stems rather than the transient abundance
of sprouts.

We found redwood growth---in terms of average total basal area of sprouts 10
years after harvest treatment---responded strongly and positively to increasing
levels of openness consistent with previous findings that redwood sprout growth
is highly sensitive to light availability and overstory density
[@oharaDynamicsCoastRedwood2010;@berrillUnderstoryLightPredicts2018;@mumaDynamicsStumpSprout2022;@oharaUnderstoryStumpSprout2007].
In contrast, the tanoak response was comparatively modest reflecting its typical
habit of forming a sub-canopy layer in these systems 
[@oharaRegenerationDynamicsCoast2017].

Although none of the treatment differences for tanoak were statistically
supported, the largest difference was between the GS and HA
treatments, suggesting that the HA treatment minimized tanoak sprout growth.
 
Shade tolerance theory predicts that at a certain overstory density, tanoak
abundance should exceed that of redwood. This crossover point appears to have
been approached in the HA and HD treatments where basal area for these two
species were very similar.

It is important to point out here that the HA and HD "high-density" treatments
in this experiment only targeted a residual overstory relative density of 20%
(that is 20% of assumed total carrying capacity of the site), and this was
selected as an upper limit to support the objective of maintaining conifer
growth [@berrillSimulatingMultiagedCoast2009]. It seems likely that at higher
overstory densities we might see tanoak abundance, in terms of total basal area,
exceed that of redwood in the understory. 

Our use of basal area as a response did not distinguish between number of stems
and size of stems. There have been numerous metrics used in attempts to assess
shade tolerance [@forresterResponseTreeRegeneration2014]. Our use of basal area
(which conflates growth and survival of sprouts) is justified given the
assumption that these are expected to be correlated in forests that don't
undergo a long harsh winter [@linSaplingGrowthSurvivorship2002]. 

Little is understood about tanoak sprout response under shade
[@wilkinsonTanoakSproutDevelopment1997;@waringRedwoodTanoakStand2008]. This
study contributes to that knowledge by describing a range of tanoak sprout
development responses with varying overstory density. Our results suggest that
tanoak sprout basal area is reduced by about half when moving from open
overstory conditions to 20% relative density.

Average redwood sprout basal area 10 years after treatment was much more
dramatically affected by overstory density and each step increase in overstory
density (GS -> LD -> HA) saw average redwood sprout basal area reduced by around
half. Aggregated retention resulted in about 1/3 greater basal area than in the
dispersed retention but the p-values for all comparisons were very high (p >= 0.2). 

In all treatments, the uncertainty in the average redwood basal area is much
greater than that of tanoak. Given that we modeled the total basal area of all
species in each vegetation plot, this suggests that variability in redwood basal
area was much greater than that of tanoak across macro plots and/or sites. The
greater relative uncertainty we observed in redwood compared to tanoak may have
to do with redwoods greater sensitivity to light conditions. We selected sites
with both north and south facing slopes and this may have led to relatively
larger differences for redwoods growth response compared to tanoak. Additional
uncertainty may be due to variable light levels within macro plots.

It is interesting to note that basal area comparisons between redwood and tanoak
resulted in steadily decreasing differences between these two species as
overstory density increases. This is in contrast to findings from this and other
studies when the focus is instead on sprout height growth. This perspective of
growth response highlights an important question for these forests: what is the
role of below-ground competition in determining the relative growth of redwood
and tanoak sprouts? This question has been raised in other studies for redwoods
[@oliverYounggrowthRedwoodStands1994] and
has been found to play play an important role in moderating growth beyond what
was expected from shade-tolerance alone, particularly with regard to soil
quality [@forresterResponseTreeRegeneration2014], or size of cut stump as a
proxy for size or resprouting root system [@berrillUnderstoryLightPredicts2018].

### Douglas-fir counts

Douglas-fir abundance was modeled using stem counts because the species
does not regenerate through sprouting and thus did not exhibit the self-thinning
found in the sprouting species. Moreover, stems were relatively few in number
and consisted largely of small seedlings, making stem density a more informative
metric than basal area for comparing responses across treatments.

Douglas-fir is a minor species of special interest due to it's commercial value
and ability to compete with redwoods in the first 100 years of stand development
[@wenselSiteIndexSystem1986]. We didn't detect statistically supported
differences between treatments in terms of basal area or stem
counts. While our observed recruitment density of Douglas-fir
seedlings may be sufficient for the eventual production of a viable cohort in a
multi-aged system [Schütz and Röhnisch, 2003, as cited in @schutzCanDouglasFir2013], only
the LD and GS treatments are likely to maintain overstory densities conducive to
Douglas-fir seedling development [@millerCanSelectionThinning2001;
@schutzCanDouglasFir2013] given the overstory basal areas recorded at the
initiation of the experiment [@mumaDynamicsStumpSprout2022]. Rapidly developing
redwood and tanoak sprouts will likely further comprise Douglas-fir seedlings
competitive ability.

### Other species

Our sampling included relatively few minor species and differences across
treatments were small. Though none of the treatment differences were
statistically supported, the largest difference occurred between the LD and HA
treatment where the latter had less basal area of minor species. While this
could be due to low numbers of occurrences of minor species and high variability
within treatments, this uniqueness of the HA treatment is found in other places
throughout our experiment results: such as for tanoak sprout basal area where
the greatest treatment difference was between the GS and HA treatments and in
the low vegetation response found in the HA treatment for the pre-PCT fuels
data. Potential differences in minor species' abundances is likely only relevant
for grand fir, due to its shade tolerance [@webbWhiskeySpringsLongterm2012]. Red
alder and western hemlock were observed during an earlier iteration of this
experiment, but were not detected with our current experimental design
[@mumaConvertingCoastRedwood2019].


## Sprout height

We found that for both redwood and tanoak, height increment and overall
height at year 10 were greatest in the Group Selection (GS) treatment, followed
by Low-Density Dispersed (LD), High-Density Aggregated (HA), and High-Density
Dispersed (HD) treatments. This pattern indicates that greater reductions in
overstory density lead to more rapid sprout growth.

This strong positive relationship between reduced overstory density and sprout
height is a consistent and well-documented finding across various species and
forest types in the literature: Understory light availability, which is
inversely related to overstory density, is a primary driver of stump sprout
growth in redwood-mixed-conifer systems
[@berrillUnderstoryLightPredicts2018;@berrillDevelopmentRedwoodRegeneration2021],
and in other systems as well
[@atwoodEffectsAlternativeSilviculture2009;@keyserStumpSproutDynamics2014;@gardinerDevelopmentWaterOak1997;@knappEarlyStumpSprout2017].

We found that redwood grew faster and achieved greater heights than
tanoak across all treatments and growth periods. For example, redwood height
increment was 0.42 m/yr greater than tanoak in the first period and 0.33 m/yr
greater in the second period. Also, redwood height growth response
was much stronger in more open conditions, while tanoak's was comparatively
modest.

The increased overstory reduction in this experiment successfully maintained
redwood sprout growth, compared to a previous study where overstory reduction
was not sufficient to maintain redwood sprout growth
[@oharaDynamicsCoastRedwood2010]. Despite substantial reductions in redwood
basal area with our high-overstory-retention treatments, especially compared to
tanoak, redwood height growth was still dominant at about 0.6 m yr^-1^. While
the aggregated high-density treatment saw marginally higher sprout height
development than the HD treatment, the difference was not large or statistically
significant. The initial harvest in both high-density treatments in this
experiment resulted in about 39 m^2^ ha^-1^. This suggests that the level of
overstory harvest prescribed by a previous growth modeling study 
[32-38 m^2^ ha^-1^, @berrillSimulatingMultiagedCoast2009] may be an upper bound
in these systems if redwood sprout growth is to be maintained until the next
partial harvest.

<!-- Marginalizing over plots was important and resulted in approximately 0.2 greater
height increment on average, compared to predictions made for an "average" plot
(one where all random effects were set to zero).  -->

## Fuel loading

### Pre-PCT 

Prior to PCT scheduled Fuel loading were comparable to other
studies in redwood systems. Our treatment level averages for duff and litter
ranged from 40 to 55 Mg ha^-1^ in plots that had post-harvest basal areas (in
2012) of 0 to 40 m^2^ ha^-1^. This was comparable to total duff and litter
loading found in 120-year-old redwood stands (range: 29 to 55 Mg ha^-1^) as well
as old-growth stands (average: 50 Mg ha^-1^) and our raw average duff and litter
depth of 6.2 cm (data not shown) was similar to that found in a range of redwood stand structures
[@finneyFuelLoadingBulk1993;@stuartRedwoodFireEcology1985;@glebockiFuelLoadingMoisture2015].
We opted to combine duff and litter into a single metric following previous
studies that found similar bulk densities for duff and litter and that
separating the two resulted in little difference from and average bulk density,
given the wide variability found in duff and litter
depths [@stuartRedwoodFireEcology1985, @finneyFuelLoadingBulk1993].

Our average total fine woody fuel loading, including one-, ten-, and one
hundred-hour-fuels (15 Mg ha^-1^) was within the range found in 120-year-old
stands (9 to 20 Mg ha^-1^, @finneyModelingEffectsPrescribed1993), double that
found in very young, mixed stands (7 Mg ha^-1^, @glebockiFuelLoadingMoisture2015), and 3 Mg ha^-1^ higher
than that found in old growth stands (12 Mg ha^-1^, @stuartRedwoodFireEcology1985).

In the following I'll compare the average fuel loadings found in this study to
those found in the "old growth" and "very young, mixed" stands referenced above.

Our one-hr fuel loading which, which averaged about 1 Mg ha^-1^ was similar to
that found in the old-growth stand, but about half that found in the very young,
mixed stand, 
 possibly due to differing stand structures and species compositions. That young
forest was dominated by young Douglas-fir and would be
expected to have different forest floor characteristics and this notion is
supported by our finding of similar 1-hr fuel loading as in the old growth
study. Another source of possible error is differences in sampling method for
1-hr fuels. We established a cutoff where redwood particles smaller than roughly
2 mm were considered as litter, rather than 1-hr fuels. If we had counted every
redwood leaf-spray, regardless of size, we would have likely found higher 1-hr
fuel loads.

Our average 10-hr fuel loading was higher than in the very young, mixed stand
(3.4 vs. 2 Mg ha^-1^) but similar to the old growth stand. It might be
reasonable here to suspect that the smaller trees in the very young, mixed stand
did not supply as much 10-hr fuels because of the sizes of their branches,
whereas branch shedding patterns in the 10-hr time lags class were more similar
between our stands and the old growth ones.

Our average 100-hr fuel loading of about 11 Mg ha^-1^ was higher than in both
the old growth stands (5 Mg ha^-1^) and the very young, mixed stands (3 Mg
ha^-1^). This may be the result of residual fuels left over from the harvest
treatment that initiated our experiment which would have been absent from the
other sites referenced here. In the very young, mixed stand for instance, 100-hr
fuels jumped to 10 Mg ha^-1^ immediately following a thinning treatment.

Our average 1,000-hr fuel loading of 42 Mg ha^-1^ was somewhat lower than found
in old growth stands (63 Mg ha^-1^) and the very young, mixed stands (54 Mg
ha^-1^). These estimates are accompanied by relatively high standard errors, but
it would not be surprising that State Park forests, with little to no recent
harvest activity would have a larger amount of large downed logs then an
actively managed forest such as ours.

The similarity in average fuel loading between our Pre-PCT stands and two
studies conducted in structurally distinct redwood forests aligns with our
finding of few statistically significant differences in fuel loading among
treatments. This result is common among other studies and is expected due to the
highly variable nature of forest fuels 
[@keaneMappingWildlandFuels2001;@keaneSpatialScalingWildland2012;@collinsVariabilityVegetationSurface2016]. 

::: {.callout-caution}
TODO: discuss observed anomalies with HA treatment in general

In all cases the largest observed differences involved the HA treatment. For
instance, for Duff & Litter was lowest in the HA treatment and highest in the HD
treatment (p = 0.10) and this trend was paralleled by a similar trend in
vegetation fuel loading as well as in tanoak basal area.

Vegetation fuel loading was lowest in the HA treatment and the greatest 
difference was between the GS and HA treatments. Lower vegetation fuel
loading in the HA treatment is reflected in the tanoak basal area results for
the HA treatment, which were collected separately
:::

In a study across California's Sierra Nevada mountain range, fine fuel loading
(including 1-, 10-, and 100-hr fuels) were found to be correlated with overstory
canopy cover and proportion of shade tolerant species and associated these
conditions, which represent recent shifts in forest composition resulting from
fire suppression, with an elevated risk of high severity fire
[@collinsVariabilityVegetationSurface2016]. The differences we observed in duff
& litter, and 1-hr fuel loads could be a result of canopy cover and understory
species composition directly, but it is likely also a result of the
microclimatic differences resulting from these different stand structures. Fine
fuel loads are a function of both recruitment and decomposition and the latter
is a function of moisture and temperature
[@pillersLeaflitterAccretionDecomposition1993;@keaneBiophysicalControlsSurface2008].
Forest floor conditions in the HA treatment may have been somewhat more moist
than the more open treatments due to sheltering but warmer than the HD treatment
due to greater light infiltration (e.g., @kaneStandConditionsAlter2021). While
the differences in duff & litter loading we observed are not likely to have a
significant impact on fire behavior, small differences in forest floor moisture
can have significant implications for prescribed burning operations. 

For both 1-hr and vegetation fuel loading, the HA treatment was most similar to
the HD treatment. In both treatments it appears that a greater density of
overstory trees would result in more twigs and less light available for growth
of vegetation at the surface. The high density treatments had less tanoak BA and
it is likely that tanoak was largely responsible for the vegetative fuel loading
differences. Vegetation fuel loading was not recorded by species but redwood and
tanoak sprouts comprised the vast majority of vegetation fuels. 

Consistently low foliar moisture content levels have been recorded for tanaok
[@kuljianEffectsSuddenOak2010] and the foliage has been compared to that of
other sclerophyllous species such as those found in chaparral ecosystems which
are characterized by intense, stand replacing fires suggesting high
flammability, particularly with low canopy base heights
[@mcdonaldAdaptationsWoodyShrubs1981;@fryerNotholithocarpusDensiflorus2008]. And
tanoak leaf litter is among the most flammable of western hardwoods and has been
compared to that of fire adapted conifers [@varnerFiresTanoakEffects2017]. To
our knowledge, no studies have examined the flammability of live tanoak foliage
or tanoak sprouts.

Our understanding of the conditions under which crown fires initiate and spread
are not well understood for several reasons and largely because of the
difficulty in observing and studying large fires
[@finneyWildlandFireBehaviour2021; @xanthopoulosCrownFire2020]. Less still is
known about crown fire behavior in this unique and transitional fuel type (mixed
conifer/tanoak sprouts). Because of the relatively low bulk density of canopy
fuels, smaller differences in fuel load equate to larger differences in total
fuel volume and resulting fire behavior, as well as implications for aerial fuel
continuity. These factors warrant more study into the fire behavior of this
unique fuel type, including its requirements for combustion, fuel moisture, and
more precise characterization of it's mass and bulk density.

It was surprising that the modeled vegetation fuel loading differences
were not more clearly differentiated because our field crew's experience was
that the GS and LD treatments were usually much more difficult to work in and
travel through due to greater understory density. 

In this study, live and dead vegetation components were combined because the focus was on
total fuel load rather than fuel moisture content. This choice allowed for a
clearer representation of the overall quantity of combustible material.
Additionally, herbaceous fuel loading was generally very low, which supported
the decision to merge herbaceous and woody loads at the transect level. By
simplifying in this way, the analysis emphasized patterns of total vegetation
loading while limiting unnecessary complexity in the analysis.


### Post-PCT

Duff and litter are not reported for post-pct stands for two reasons. First,
these are not expected to have changed significantly given the relatively short
timespan before and after PCT. Second, our sampling protocol did not make it
clear how to quantify the loading for leaves attached to recently cut branches,
especially given that these "suspended litter" particles were in a state of
active transition to the ground, as they dry, abscise, and sift through the
coarser woody fuels as they make their way to the ground. This class may deserve
more attention because of it's potentially dynamic relationship with the timing
of prescribed fires: as suspended particles settle and begin to decompose they're
bulk density changes and bulk density is an important determinant of fire
behavior.

Vegetative growth following thinning and harvest is an important consideration
for fire informed management. In our experiment, greater overstory retention
resulted in lower understory size and density. Therefore, 10 years of growth
(followed by PCT) led to some increase in average fine woody fuel loading,
particularly in the dense understories of the GS and LD treatments. One-hr fuels
increased most in the GS and LD treatments but there was also an unexpected
increase in 1-hr fuels in the HD treatment compared to the HA treatment which
had a negligible increase. Ten-hr fuels increased most in the GS and somewhat in
the LD treatment, reflecting the more rapid growth seen in these treatments
compared to the others.

Pre-commercial thinning resulted in little change in 1,000-hr fuels, as thinned
sapling stems were mostly under three inches, although a potential increase
observed in the HD treatment may have been a result of some previously retained
canopy trees being cut (12 inches DBH was the prescribed upper limit for
thinning). The model selection process resulted in slightly different models
after pre-commercial thinning, compared to before thinning for a given fuel
class. The model selection process was guided by balancing parsimony, AIC, and
the production of well distributed residuals. As predicted fuel load variability
increased along with predicted fuel loads following PCT, model selection tended
towards more complex models that accounted for this variability--particularly
for 1- and 100-hr fuels.

It can be seen from this analysis, resulting surfaces fuel conditions are
expected to be the result of a complex interaction of understory stand
productivity, overstory retention, and decomposition rate. Whether any of the
differences we observed result in a significant difference in prescribed or wild
fire will need to be tested by those disturbances. It is possible that the
elevated 10-hr loads in the GS and to a lesser degree, the LD treatments may
represent greater fuel continuity which could support prescribed fire
operations. Likewise, the HA treatment's lower fuel loading across classes could
signify patchy fuel distribution.


# Limitations and future work

Throughout this multi-faceted analysis there were several limitations that
arose.

Basal area comparisons among treatments and with other species within a
treatment for tanoak were confounded by the fact that tanoak produced an
abundance of small diameter sprouts, especially in the HA and HD treatments
treatment (383 in HA vs 496 in HD, data not shown). Stems smaller than 2.54 cm
DBH were tallied. To facilitate basal area analysis, I assigned each of these
the possibly inaccurate midpoint diameter of 1.27 cm. Thus, the basal area of
these bushier tanaok in the HD and HA treatments may be slightly artificially
elevated. On the other hand, the general trend of treatment effect on tanaok
basal area response was mirrored in the vegetation fuel loading data which was
collected separately, lending support to the idea that the HA treatment may have
minimized tanoak sprout growth.

In the analysis of sprout basal area, aspect would be an important consideration
for sprouts growth response. Reducing our uncertainty around redwood basal area
may require better incorporating the effect of aspect into our model. Also
regarding aspect, it seems likely that the effect of site on sprout growth was
bi-modal (due to our combination of predominately north- and south-facing site
aspects) and thus the regularization imposed by our random effects for sites
(assumed to be normally distributed) was likely inappropriate.

Our method of calculating vegetation fuel loading (estimated percent cover times
estimated height within an estimated cylinder) might have been overly imprecise.
Additionally, given the importance of understory light to the processes of
surface fuel decomposition as well as for understory growth, including aspect
might have led to better explanatory power in our models. Our plots were
established over a range of aspects, but it is plausible that differences in
aspect outweighed differences between treatments. We had hoped that the
inclusion of site and treatment as nested random effects would have captured
site and block level differences in aspect. Additionally, aspect is largely a
proxy for insolation, and this may have also varied with shade conditions (very
large trees or road cuts) outside of the plot.

The simple method we used probably over-estimated vegetation fuel loading,
evidenced by the fact that the large fuel loading differences measured for the
vegetation class are not reflected in the increase in fine fuels following PCT.
Although the contribution of slash foliage is not accounted for, it appears our
method may have over predicted vegetation loading by around a factor of three
under the assumption that the majority of the difference in vegetation fuels
should be captured by the sum of the differences in fine fuels.

An important consideration for redwood sprouts in this experiment is that after
thinning, a fraction of existing sprouts will be retained. The retained sprouts
will generally be the largest and most vigorous. An interesting question that is
overlooked by our focus on the total basal area of sprout regeneration is if any
treatment produced larger individuals that would eventually be selected for
retention. 

Surface fuel moisture and wind speed are two variables which we did not study
but which have a strong influence on fire behavior and are also affected by
overstory density and arrangement. Given the relatively modest difference we
observed in fuel loads, it seems likely that those unmeasured factors would have
a greater bearing on fire outcomes and warrant further study in these unique
forest systems.


# Conclusions and management implications

This study demonstrates the critical trade-off between maximizing redwood
productivity and managing fuel hazards. Harvesting techniques that promoted the
greatest redwood productivity and growth also resulted in significantly higher
levels of live vegetation fuels before pre-commercial thinning.

Consequently, following the PCT, these high-productivity treatments also
generated higher volumes of fine dead fuels. This shows that successful
pyrosilviculture (not unlike traditional silviculture) must balance the goals of
growth and yield with fuels management. Maximizing the former also increases the
volume of slash fuels generated during tending treatments.

This study also confirms that redwood and tanoak respond differently to varying
levels of canopy openness. Redwood basal area and height growth responded
strongly and positively to increasing openness.

However, the findings suggest that the highest retention treatments approach a
critical threshold where tanoak's competitive ability increases relative to
redwood. When basal area is used as the measure of competitive advantage, this
threshold occurred in the HD treatments, at overstory retentions of 20% relative
density, or 39 m^2^ ha^-1^.  

A significant result of this research involved the broader context of forest
stewardship. This study acknowledged the importance of incorporating indigenous
perspective, particularly from the Northern Pomo, the original stewards of these
lands, for responsible management of keystone species like tanoak. Tanoak is
culturally essential to the Pomo people as a principal food source, underscoring
the need for genuine and collaborative partnerships in future projects to ensure
respectful and sustainable stewardship.

Methodologically, the high uncertainty observed in light-sensitive redwood basal
area, as well as in vegetation fuels suggests that future modeling efforts may
need to explore other important sources of variation, like aspect.

::: {.content-visible when-format="docx"}

# References

:::


```{r}
#| include: false
#| eval: false

grand_mean_table <- function(mods) {
  dplyr::mutate(
    mods,
    grand_mean = tibble::as_tibble(emmeans::emmeans(.emmeans, ~1))
  ) |>
    dplyr::select(class, grand_mean) |>
    tidyr::unnest(grand_mean)
}
grand_mean_table(fuel_tmb$pre) |> tinytable::tt()
grand_mean_table(fuel_tmb$post) |> tinytable::tt()

# average grand mean differences
bind_cols(
  filter(grand_mean_table(fuel_tmb$pre), as.character(class) != "dufflitter"),
  filter(grand_mean_table(fuel_tmb$post), as.character(class) != "veg_diff")
) |>
  mutate(
    diff = response...10 - response...3
  )

# what is the by-treatment difference in the fine-fuel change vs. the vegetation
# change, because most of the latter should be captured by the former.
fuel_tmb |>
  bind_rows(.id = "phase") |>
  unnest(emmeans) |>
  group_by(class, treatment) |>
  select(phase, response) |>
  pivot_wider(names_from = phase, values_from = response) |>
  drop_na() |>
  transmute(diff = post - pre) |>
  ungroup() |>
  pivot_wider(names_from = class, values_from = diff) |>
  mutate(fine_dif = onehr + tenhr + hundhr, veg_dif = -veg, .keep = "unused") |>
  mutate(factor = veg_dif / fine_dif)
```
