# Methods

## Site description

Situated within the unceded ancestral territory of the Northern Pomo, near the
coast of northern California, the 20,000-ha Jackson Demonstration State Forest
(JDSF)
was established in 1947 after being cut over multiple times starting in 1862.
The mission of the JDSF is to remain in timber production for research and
demonstration purposes. The predominant cover type is redwood, tanoak, and
Douglas-fir forest at elevations ranging from 20 m near the coast to 700 m
inland. The climate is Mediterranean with cool, wet winters and an average
annual precipitation of about 1150 mm. The sites that compose my experiment
were all redwood dominated with significant components of tanoak and Douglas-fir
and were well stocked with trees 80 to 100 years old. All of my study sites are
between 13 and 16 km from the Pacific Ocean at elevations between 130 and 300 m,
on well-drained, sandstone-derived soils. The sites are located on various
aspects on mid to upper-slope positions (@fig-site-map), and the site quality is
classified as Site Class II [@lindquistEmpiricalYieldTables1963;
@webbWhiskeySpringsLongterm2012].

![The site locations and topography for my study plots. The red box delineates
the area of the topographical map seen in the background. JDSF = Jackson
Demonstration State Forest.](../figures/site_map_2.png){#fig-site-map}

## Study design

In 2012, four treatments were replicated at four different sites. The treatments
were: group selection (GS), high-density dispersed retention (HD), high-density
aggregated retention (HA), and low-density dispersed retention (LD). The GS
treatment is composed of a circular 1-ha opening in which all trees were
removed, surrounded by a 50-meter buffer of light thinning in which less than
1/3 of the basal area was removed. The remaining treatments were applied over
2-hectare treatment units. The target post-harvest density was specified in
terms of relative density using an assumed upper stand density index (SDI) limit for
redwood of 2,470 stems ha^-1^ [@reinekePerfectionStanddensityIndex1933]. The
target residual relative density for the HA and HD treatments was 21% (SDI =
520), and the for the LD treatment it was 13% (SDI = 320). These densities were
chosen to balance the objectives of stand volume production and individual tree
growth assuming a subsequent, similar harvest after 20 years
[@berrillSimulatingMultiagedCoast2009].

After harvesting, a single 0.2-hectare square macro plot was established in the
center of each treatment unit. Approximately 25 redwood and 25 tanoak sprout
clumps that were well distributed across the plot, were selected for
measurement. Additionally, for redwood, sprout clumps were selected evenly from
those with, and without residual standing trees.

Ten years after the initial harvest, regeneration plots and fuel transects were
established within the macro plot (@fig-plot-layout). Circular regeneration
plots with a 4-meter radius were established 10 meters from each macro plot
corner, towards the plot center. Terminating at the center of each of these
regeneration plots, 10-meter fuel transects were established parallel to the
macro plot edges. Live fuels were estimated in 1-meter radius "sampling
cylinders" at the five-, and nine-meter locations along each transect.

Following year 10 measurements, all plots received a PCT
treatment where the objective was to release merchantable conifers such as
redwood and Douglas-fir from competition. Competing trees and shrubs were cut,
lopped, and scattered within the measurement plots and fuel transects were
re-measured.

![A diagram of the fuel sampling design depicting a 0.2-hectare macro plot
(black outline), fuels transects (black lines), sampling cylinders (orange
circles) where duff, litter, and live and dead vegetation were measured, and
vegetation sub-plots (green circles), where regeneration density and diversity
were quantified.](../figures/fuel_sampling_layout.png){#fig-plot-layout}

## Data collection

### Regeneration

Ten years after the initial harvest, four regeneration plots (4-m radius)
were established within each macro plot (@fig-plot-layout). All regenerating
trees (sprouts and seedlings) within the plot were recorded. Regenerating trees
less than 5 cm diameter at breast height (1.4 m) were tallied by 2.5 cm size classes and the
actual DBH of all other regenerating trees were recorded. This allowed for an
estimation of sprout and seedling density by species. 

### Sprout heights

Sprout height data were collected during the winter at years 1, 5, and 10
following the initial harvest. Sprout heights at each period were based on the
tallest individual within the selected redwood and tanoak clumps at the time of measurement with a height pole
placed at the same location on the ground at each measurement period. The
observer eliminated parallax by observing from a location up-slope, level with
the height of the sprout. Sprout DBH for only redwood was collected in year 10.

### Fuels

Also at 10 years after the initial harvest, fuel transects were established and
sampled according to the FIREMON protocol [@lutesFIREMONFireEffects2006], with
some adaptations that were unique to this project. This protocol is very similar
to that of @brownHandbookInventoryingDowned1974. One-, 10-, 100-hr, and 1000-hr
(or coarse woody) fuels were those less than 0.635 cm, 0.635 to 2.54 cm, 2.54 to
7.62 cm and those 7.62 cm and greater, respectively and included only dead and
downed woody fuels (not those attached to live vegetation, or standing dead).
For pre-PCT fuel measurements, transect lengths were two, two, and four meters
for 1-, 10-, and 100-hr fuels, respectively. For post-PCT measurements, the
length of the 1-hr fuel transect was reduced to one meter because of the
dramatic increase in these fuels. Coarse woody fuels were measured along the
entire 10-meter transect.

Redwoods, like other species in Cupressaceae, shed branchlets instead of
individual leaves. This leads to difficulty in distinguishing "litter" from 1-hr
fuels. We chose to use an estimated cutoff of about 2 mm for redwood branchlets,
where larger pieces were considered 1-hr fuel and smaller pieces were considered
part of the litter layer. We did not distinguish between "leafy" and "awl like"
leaf shapes [@grahamStructureDownedWoody2009].

Live vegetation percent cover and average height were estimated in
1-meter-radius "sampling cylinders" as described in the FIREMON protocol
[@lutesFIREMONFireEffects2006]. A notable exception is that the sampling
cylinders were allowed to extend to the (average) top height of the live fuels
that were continuous within less than a meter of the ground. This resulted in
average live vegetation heights that could sometimes reach near the height of
the sprouts. Average live fuel heights that were above two
meters were estimated with the help of a clinometer. Live vegetation percent
cover was estimated for four vegetation classes: live woody fuels, dead woody
fuels, live herbaceous fuels, and dead herbaceous fuels. Dead "live" fuels
included dead fuels attached to live plants, or those still rooted in the
ground. Particles in these conditions are not counted as downed woody fuels when
tallying fine and coarse woody fuels along fuel transects.

Average vegetation height was recorded for two classes: the average height of
all woody fuels and the average height of all herbaceous fuels. These estimates
pertain to the particles present in the sampling cylinder, and not the
area-average, thus a cylinder with only one percent cover, could still have an
average height of two meters, i.e., the empty space within the cylinder does not
affect the average height. The average height and percent-cover estimates are
visual estimations and efforts were made to compare these frequently to ensure
that estimates among observers were consistent. Percent cover estimates were
discrete, rounded to the nearest class in the set: 0.5, 3, 10, and all
subsequent 10 percent increments up to 100 percent.

The depth of duff and litter was measured at one representative location within
each of the two, 1-meter-radius sampling cylinders along each transect. When
duff and litter conditions varied greatly in a single sampling cylinder, a
location was chosen to represent the average of conditions within the cylinder. 

Fuel bed depth was estimated as the average height of the fine and coarse woody
debris components within each sampling cylinder. Theoretically, this included
litter, but not duff. This estimate was not described in the FIREMON protocol,
but it was designed to be made in a similar manner as described for vegetation
heights.

## Analysis

An analysis was conducted in three stages, one for each of the three response
categories: fuels, sprout size, and regeneration density. All analyses were
conducted using R and attempts were made to document all data, decisions, and
techniques within a Quarto notebook, which is published at
`https://fisher-j.github.io/multi-age`. All response variables were analyzed
using multi-level models to account for the inherent nesting structure of the
data, including multiple measurements of sprouts over time, where applicable.
Grouping levels were included in the models if their variance estimate was
determined to be significant. If including a grouping level resulted in
a meaningful change in estimates or confidence intervals, the grouping level was
kept. Because the overall objective was to detect differences between
treatments, treatment was used as the primary independent variable. Model
development and selection were carried out using Akaike information criterion,
 and visualization of (probability integral)
transformed residuals [@hartigDHARMaResidualDiagnostics2022]. Models were built
using the R package GLMMtmb, which provides a consistent framework for exploring
different response distributions and link functions as well as the ability to
model variance as a function of predictors [@brooksGlmmTMBBalancesSpeed2017].

Models were interpreted using estimated marginal means calculated with the  R
packages `marginaleffects` and `emmeans` [@lenthEmmeansEstimatedMarginal2021;
@arel-bundockHowInterpretStatistical2024]. Predictions incorporating the effects
of all model components were made on the response scale for a grid of predictors
consisting of all unique combinations of factors in the data that were used in
at least one component of a given model (we didn't have numeric predictors)
except in the case of tree heights where predictions were made for each
observation in the data set. Standard errors for the predictions were calculated
using the delta method. Predictions were averaged across non-focal predictors
(especially "random" effects) to obtain the population estimates of marginal
means. These means are expected to be applicable to other treatments when
conducted across equal proportions of sites with conditions similar to those
used in my study. Notably, my population estimates assume equal proportions of
north and south facing aspects.

The formulas below use $\beta$ to represent fixed effects and $\alpha$ to
represent random effects. Subscripts indicate the variable associated with each
effect. Superscripted Greek letters indicate the model component where fixed or
random effects are present in more than one component (e.g., $\mu$ for the
conditional model, $\pi$ for the hurdle model, and $\phi$ for the dispersion
model). A "hurdle gamma" distribution is used for models of basal area and fuels
and is defined as

$$
\text{hurdle\_gamma}(y_i \mid \pi_i, \mu_i, \phi_i) = 
\begin{cases}
1-\pi_i & \text{if } y_i = 0 \\
\pi_i \cdot \text{Gamma}(y_i \mid \mu_i, \phi_i) & \text{if } y_i > 0
\end{cases}
$$
.

### Regeneration 

#### Basal area

Sprout count data from my 4-meter-radius regeneration plots were converted to
basal area per acre per species. Tallies of species by size class for sprouts
less than 5 cm dbh were converted to diameters using the class midpoint (1.27 or
3.81 cm) before calculating basal area per acre. Minor species (i.e., those
other than redwood, tanoak, and Douglas-fir) were combined into an "other"
category. Missing species on a plot were made explicit by assigning a value of 0
m^2^ ha^-1^ for that species and plot. 

Composition of regeneration in terms of basal area per acre represented by each
species in a 4-meter radius vegetation plot 10 years after treatment was modeled
as a gamma distribution with a log link with fixed effects for treatment and
species, and random intercepts for site x species interaction. Dispersion was
modeled separately as a function of species, using a log link and the rate of
zeros was modeled using the logit link, for each species as well:


$$
Y_i \sim \text{hurdle\_gamma}(\pi_i, \mu_i, \phi_i)
$$

$$
\text{logit}(\pi_i) = \beta^{\pi}_0 + \beta^{\pi}_{\text{spp}} \cdot \text{Species}_i
$$

$$
\log(\mu_i) = \beta^{\mu}_0 + \beta^{\mu}_{\text{trt}} \cdot \text{Trt} + \alpha_{j[i]}
$$

$$
\log(\phi_i) = \beta^{\phi}_0 + \beta^{\phi}_{\text{spp}} \cdot \text{Species}_i
$$

$$
\alpha_j \sim N(0, \sigma^2_j)
$$


- $Y_i$: Total basal area per hectare for each species in a 4-meter radius
  regeneration plot.
- $\pi_i$: Probability that $Y_i > 0$
- $\mu_i$: Mean of positive values.
- $\phi_i$: Dispersion parameter for Gamma distribution
- $\alpha_j$: Group effect pertaining to a site:species interaction

#### Douglas-fir seedling counts

Counts of regenerating Douglas-fir seedlings per vegetation plot were
analyzed for differences between harvest treatments using a negative binomial
response with a log link, fixed effects for treatment, random effects for sites
and macro plots within sites.


$$
Y_i \sim \text{NB1}(\mu_i, \phi); \quad \text{where} \quad Var(Y_i) = \mu_i +
\phi \mu_i
$$

$$
\log(\mu_i) = \beta_0 + \beta_{\text{trt}} \cdot \text{Trt}_i +
\alpha_{j[i]} + \alpha_{k[i]}
$$

$$
\alpha_{j} \sim \operatorname{N}(0, \sigma^2_{j}), \quad \alpha_{k} \sim \operatorname{N}(0, \sigma^2_{k})
$$

- $Y_i$: Count of Douglas-fir seedlings in a 4-meter radius vegetation plot.
- $\mu_i$: The expected count for vegetation plot $i$.
- $\beta_{\text{trt}}$: Fixed effect for harvest treatment.
- $\alpha_j$: Random intercept for site.
- $\alpha_k$: Random intercept for plots within sites. 

### Sprout heights

Two metrics were analyzed from the sprout height data: height increment (m
year^-1^), and total height (m) at year 10. 

In both models, a random slope for species is included for each
macro plot. This specifies a general (unstructured) covariance matrix that
allows the random effect variance to differ by species (heteroscedasticity) and
allows for non-zero correlations between species-level effects within the same
plot (e.g., assessing if plots that are favorable for one species are also
favorable for others). This variance-covariance matrix takes the following form,
where $A$, $B$, and $C$ represent different species:

$$
\boldsymbol{\Sigma}_{\text{macro}} =
\begin{pmatrix}
\sigma_A^2 & \rho_{AB}\sigma_A\sigma_B & \rho_{AC}\sigma_A\sigma_C \\
\rho_{AB}\sigma_A\sigma_B & \sigma_B^2 & \rho_{BC}\sigma_B\sigma_C \\
\rho_{AC}\sigma_A\sigma_C & \rho_{BC}\sigma_B\sigma_C & \sigma_C^2
\end{pmatrix}
$$
.

#### Height increment

For height increment, there were two
measurements for each tree: increment for years 1 to 5 and increment for years 5
to 10. Thus, analysis of these data included `tree` as a candidate random
effect. While not making a difference for analysis results, it is worth noting
that these data were structured differently from the other datasets in that
`plot` was made a globally unique identifier, thus making explicit the nesting
of plots within sites or treatments and eliminating the need to specify this
nesting structure in the R code model formulas.

The selected height increment model used a normal response distribution on the
identity link. It included treatment, growth period, species, and the
interaction of species and growth period as fixed effects. A random intercept
was included for tree (multiple observations) and macro-plot, and another
random effect allowed the response to vary by species differently for each macro
plot. The dispersion parameter for the response was modeled (with a log link) as
a function of treatment, growth period, species and all three-way interactions
.  

$$
Y_i \sim \operatorname{N}(\mu_i, \sigma^2_i)
$$

$$
\mu_i = \beta_0^{\mu} + \beta_{\text{trt}}^{\mu} \cdot \text{Trt}_i + \beta_{\text{year}}^{\mu}
\cdot \text{Year}_i + \beta_{\text{spp}}^{\mu} \cdot \text{Spp}_i +
\beta_{\text{spp:year}}^{\mu}(\text{Spp}_i \times \text{Year}_i) +
\alpha_{\text{tree}[i]} + \alpha_{\text{macro}[i],\text{spp}[i]}
$$

$$
\log(\sigma_i) = \beta^{\sigma}_0 + \beta^{\sigma}_{\text{trt}} \cdot \text{Trt}_i + \beta^{\sigma}_{\text{yr}}
\cdot \text{Year}_i + \beta^{\sigma}_{\text{spp}} \cdot \text{Spp}_i + \dots + \beta^{\sigma}_{\text{3way}}
(\text{Trt}_i \times \text{Year}_i \times \text{Spp}_i)
$$

$$
\alpha_{\text{tree}} \sim N(0, \sigma^2_{\text{tree}})
$$

$$
\alpha_{\text{macro}, \text{spp}} = \begin{pmatrix} \alpha_{\text{macro}_1, \text{spp}_1} \\
\alpha_{\text{macro}_1, \text{spp}_2} \\
\vdots \\ \alpha_{\text{macro}_j, \text{spp}_k} \end{pmatrix} \sim \operatorname{N}(\mathbf{0},
\boldsymbol{\Sigma}_{\text{macro}})
$$

- $Y_i$: Height increment (m yr^-1^) for sprout observation $i$.
- $\mu_i$: Mean height increment for observation $i$.
- $\sigma^2_i$: Variance of height increment for observation $i$.
- $\alpha^{\mu}_{\text{tree}}$: Random intercept for tree.
- $\alpha^{\mu}_{\text{macro}, \text{spp}}$: Random effect for species, co-varying
  within macro plot.
- $\boldsymbol{\Sigma}_{\text{macro}}$: Unstructured variance-covariance matrix for species
  within macro plot.


#### Height at year 10

Sprout heights at year 10 were modeled with a normal response and a log link.
The best model included species and treatment, but no interactions in the fixed
effects. This suggests that treatments do not affect species differentially in
terms of the mean response (height at year 10). It also included a model for
dispersion (log link) with predictors species, treatment, and their interaction
.

$$
Y_i \sim \operatorname{N}(\mu_i, \sigma^2_i)
$$

$$
\log(\mu_i) = \beta_0^{\mu} + \beta_{\text{trt}}^{\mu} \cdot \text{Trt}_i + \beta_{\text{spp}}^{\mu} \cdot \text{Spp}_i + \alpha_{\text{spp}[i], \text{macro}[i]}
$$

$$
\log(\sigma_i) = \beta^{\sigma}_0 + \beta^{\sigma}_{\text{trt}} \cdot
\text{Trt}_i + \beta^{\sigma}_{\text{spp}} \cdot \text{Spp}_i +
\beta^{\sigma}_{\text{trt:spp}}(\text{Trt}_i \times \text{Spp}_i)
$$

$$
\alpha_{\text{spp}, \text{macro}} = \begin{pmatrix} \alpha_{\text{spp}_1,
\text{macro}_1} \\ \alpha_{\text{spp}_1, \text{macro}_2} \\
\vdots \\ \alpha_{\text{spp}_j, \text{macro}_k} \end{pmatrix} \sim
\operatorname{N}(\mathbf{0}, \boldsymbol{\Sigma}_{\text{spp}, \text{macro}})
$$

- $Y_i$: Height at year 10 for tree $i$.
- $\mu_i$: Mean height at year 10 for tree $i$.
- $\sigma^2_i$: Variance of height at year 10 for tree $i$.
- $\alpha_{\text{macro}, \text{spp}}$: Random effect for species, co-varying
  within macro plot.
- $\boldsymbol{\Sigma}_{\text{macro}, \text{spp}}$: Unstructured variance-covariance matrix for species
  within macro plot.


### Fuels

Fuel load in Mg ha^-1^ was estimated for 1-hr, 10-hr, 100-hr, combined duff and
litter ("duff/litter"), 1,000-hr, and live vegetation fuels at the transect
level. Any transect where a fuel type was not observed was assigned a value of
zero for that class and transect. Fuel load for 1- through 1,000-hr fuels were
calculated using the method in @brownHandbookInventoryingDowned1974. The
required size-class specific parameters (specific gravity, particle inclination,
and average diameter) were derived from a previous study where I used parameters
averaged across all of the measured plots [@glebockiFuelLoadingMoisture2015].
For 1,000-hr fuels, decay classes 1-3 were considered "sound" and decay classes
4 and 5 were considered "rotten" for the purpose of calculating load and these
loads were combined. Duff and litter were measured at two locations along each
transect and these were averaged at the transect level. We did not measure the
bulk density of duff and litter fuels, but based on findings in other studies in
the redwood region, we opted to combine these classes into a single fuel class,
using an average bulk density found across those studies of 7.73 Mg ha^-1^
[@finneyFuelLoadingBulk1993;@stuartRedwoodFireEcology1985;@kittredgeComparisonForestFloors1940].
Vegetation fuel load was calculated using bulk density constants of 8 Mg ha^-1^
m^-1^ for herbaceous fuels and 18 Mg ha^-1^ m^-1^ for woody components
[@gangiFIREMONDatabaseUser2006]. Live and dead components were combined to
calculate herbaceous and woody loading. Herbaceous and woody fuel loads were
then combined and averaged at the transect level (two measurements per transect)
to determine total vegetation loading.

Gamma distributed, linear multi-level models, with a log link were used to model
fuel load response (Mg ha^-1^) for all fuel classes. Random intercepts were
specified for three levels of nesting, representing sites, macro plots, and
transect corners. A hurdle component with logit link was used for predicting
zeros in all models except for the duff & litter model. Dispersion components
were included where needed, based on AIC model selection. Models were fit
separately for pre- and post-PCT fuel measurements. Duff and litter were not
measured post-PCT, and vegetation difference was only modeled post-PCT.

$$
Y_i \sim \text{hurdle\_gamma}(\pi_i, \mu_i, \phi_i)
$$

$$
\log(\mu_i) = \beta^{\mu}_0 + \beta^{\mu}_{\text{trt}} \cdot \text{Trt}_i +
\alpha_{\text{site}[i]} + \alpha_{\text{macro}[i]} + \alpha_{\text{corner}[i]}
$$

Any model component not explicitly defined below was modeled with only an
intercept:

$$
\text{logit}(\pi_i^\cdot) = \beta^{(\pi,\cdot)}_0
$$

$$
\log(\phi_i^{\cdot}) = \beta^{(\phi,\cdot)}_0
$$

- $Y_i$: Fuel load (Mg ha^-1^) for transect $i$.
- $\pi_i$: Probability that $Y_i > 0$, the hurdle component.
- $\mu_i$: Mean of positive values.
- $\phi_i$: Dispersion parameter for Gamma distribution.
- $\alpha_{\cdot}$: Random intercepts for site, macro plot, and corner.
- $\beta^{\cdot}_{\cdot}$: Fixed effects for intercepts and treatment
  levels for mean, hurdle, and dispersion components
.

#### Pre-pct

For the Duff & Litter model, there was no hurdle component because there were no
zeros in the data, and the dispersion parameter was modeled with only an
intercept:

$$
\text{logit}(\pi_i^{\text{dufflitter}}) = \beta^{(\pi,\text{dufflitter})}_0
$$

For the 10-hr fuel model, the hurdle
and the dispersion components were modeled as functions of treatment.

$$
\text{logit}(\pi_i^{\text{10hr}}) = \beta^{(\pi,\text{10hr})}_0 +
\beta^{(\pi,\text{10hr})}_{\text{trt}} \cdot \text{Trt}_i
$$

$$
\log(\phi_i^{\text{10hr}}) = \beta^{(\phi,\text{10hr})}_0 +
\beta^{(\phi,\text{10hr})}_{\text{trt}} \cdot \text{Trt}_i
$$
.

#### Post-pct

After PCT, duff & litter was not modeled, vegetation difference was added. Model
selection resulted in somewhat more complex models for dispersion ($\phi$) and
hurdle ($\pi$) components. For 1-hr fuels the dispersion component included
treatment and site predictors:

$$
\log(\phi_i^{\text{1hr}}) = \beta^{(\phi,\text{1hr})}_0 +
\beta^{(\phi,\text{1hr})}_{\text{trt}} \cdot \text{Trt}_i + 
\beta^{(\phi,\text{1hr})}_{\text{site}} \cdot \text{Site}_i
$$
.

For 100-hr fuels, the dispersion and hurdle components included treatment
and site predictors:

$$
\log(\phi_i^{\text{100hr}}) = \beta^{(\phi,\text{100hr})}_0 +
\beta^{(\phi,\text{100hr})}_{\text{trt}} \cdot \text{Trt}_i + 
\beta^{(\phi,\text{100hr})}_{\text{site}} \cdot \text{Site}_i
$$

$$
\text{logit}(\pi_i^{\text{100hr}}) = \beta^{(\pi,\text{100hr})}_0 +
\beta^{(\pi,\text{100hr})}_{\text{trt}} \cdot \text{Trt}_i + 
\beta^{(\pi,\text{100hr})}_{\text{site}} \cdot \text{Site}_i
$$
.

The dispersion and hurdle components for the rest of the fuel models included
only an intercept.

Dispersion models with treatment as the only predictor were included for 1-hr
and 100-hr fuel classes. All models included a hurdle portion to model zeros
using a logit link. For 100-hr fuels, the hurdle portion included treatment and
site as predictors. For the rest, a constant rate of zeros for all observations
was used.
