execute:
  freeze: auto
  # keep-md: true

project:
  type: book
  output-dir: ../docs
  execute-dir: project

book:
  title: >
    Regeneration and Fuel Loads with Varying Overstory Retention in Redwood
    Stands 10 Years after Transformation to Multiaged Management
  author: Judson Fisher
  date: 2024-02-13

bibliography: 
  - multi-age.bib
  - RW_Fire.bib
