format:
  html:
    toc-depth: 4
  docx:
    toc: true
    toc-depth: 4

project:
  pre-render: cp thesis/_index.qmd index.qmd
  output-dir: ../docs
  type: book

book:
  title: >
    Regeneration and Fuel Loading with Varying Overstory Retention in Redwood
    Stands 10 Years after Transformation to Multiaged Management
  author: Judson Fisher
  date: 2024-02-13
  output-file: jf-thesis
  downloads: docx
  chapters:
    - index.qmd
    - thesis/introduction.qmd
    - thesis/methods.qmd
    - thesis/results.qmd
    - thesis/discussion.qmd 
  sidebar:
    contents:
      - text: "Download docx"
        href: "jf-thesis.docx"
