project:
  type: book
  output-dir: ../docs
  execute-dir: project
execute:
  freeze: auto
format:
  html:
    toc-depth: 4

book:
  title: "Redwoood multi-age experiment"
  author: "Judson Fisher"
  date: "2023-05-22"
  chapters:
    - index.qmd
    - part: "Fuels"
      chapters:
        - data_description.qmd
        - calculate_fuel_loading.qmd
        - fuel_data_exploration.qmd
        - hypothesis_test.qmd
    - part: "Sprouts"
      chapters:
        - sprouts_import_data.qmd
    - work_log.qmd

bibliography: 
  - multi-age.bib
  - RW_Fire.bib
