project:
  type: website
  pre-render: 
    - cp _index.qmd index.qmd
    - cmd.exe /c "scripts\make_git_log.bat"
  output-dir: ../docs
  render:
    - "**/*.qmd"
    - "!analysis/"
    - "!thesis/"

format: html
