format:
  html:
    toc-depth: 4

project:
  pre-render: cmd.exe /c "scripts\make_git_log.bat"

book:
  sidebar:
    collapse-level: 1
    tools:
      - icon: save
        menu:
          - text: Download docx format
            href: "jf-thesis.docx"
  chapters:
    - index.qmd
    - part: "Full analysis"
      chapters:
        - fuel_data_description.qmd
        - calculate_fuel_loading.qmd
        - fuel_data_exploration.qmd
        - fuel_data_modeling.qmd
        - sprouts_import_data.qmd
        - sprout_data_exploration.qmd
        - sprout_modeling.qmd
        - regen_data_import.qmd
        - regen_visualize.qmd
        - work_log.qmd
    - introduction.qmd
    - methods.qmd
    - results.qmd
    - discussion.qmd 
