project:
  type: book
  output-dir: ../docs
  execute-dir: project

book:
  title: "Redwoood multi-age experiment"
  author: "Judson Fisher"
  date: "2023-05-22"
  chapters:
    - index.qmd
    - work_log.qmd
    - data_description.qmd

bibliography: multi-age.bib
