project:
  execute-dir: project
execute:
  freeze: auto
  # keep-md: true

bibliography: "{{< env GLOBAL_BIB >}}"
csl: apa.csl
website:
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
