project:
  type: book
  output-dir: ../docs
  execute-dir: project

book:
  title: "Redwoood multi-age experiment"
  author: "Judson Fisher"
  date: "2023-05-22"
  chapters:
    - index.qmd
    - data_description.qmd
    - calculate_fuel_loading.qmd
    - work_log.qmd

bibliography: 
  - multi-age.bib
  - RW_Fire.bib
