---
output-file: "thesis-index"
---

## Abstract {.unnumbered}

This is an analysis of the 10-year re-measure of the Redwood multi-age
experiment which is maintained by Dr. Pascal Berrill, professor of silviculture
at Cal-Poly Humboldt, in conjunction with the Jackson Demonstration State Forest
in Mendocino County, California. The multi-aged experiment explores the
regeneration response of several species following different harvesting
techniques including group selection, aggregated retention, and high/low
dispersed retention. The 10-year re-measure data includes surface fuel
characterization and regeneration density.

## Acknowledgements {.unnumbered}

I would like to thank my advisor Pascal Berrill for his long standing support
and unwavering flexibility in accommodating my not-always-most-direct path and
unfailing confidence in my abilities. I'm indebted to his long-time investment
in me through the sharing of his knowledge and experience and enriched by his
friendship. My other committee members, Jeffrey Kane, and Rosanna Overholser
have also offered their long-suffering support, and friendship and have been
invaluable resources and trusted sounding blocks as I have navigated this
process. Their direction, advice, and encouragement were instrumental in my
continued commitment to completing my thesis. This thesis would not have been
possible without the administrative support of Nona Minerva, Erin Kelly, and
Eric Riggs. My field data would have been measly at best were it not for the
dedicated efforts of our field crew: Allen Cooper, JD Wilder, Destiny Rivera,
Keith Shuttle, Aidan Jack Murphy, Ian Blundell, Hanna Upton, and Ally Medina.

I acknowledge that this research was conducted on the unceded territory of the
Northern Pomo tribes, the original stewards of these lands. I recognize and
deeply regret our failure to engage with the tribe during our fieldwork. This
omission carries significant implications for the responsible management of
these forest ecosystems, particularly regarding the health and development of
tanoak, a keystone species and a principal food source sustaining the Pomo
people since time immemorial. I understand the importance of incorporating
Indigenous knowledge into ecological research and management, and I sincerely
hope that future projects on these lands will be conducted in genuine and
collaborative partnership with Pomo tribal members. I believe their expertise is
essential to ensuring the respectful and sustainable stewardship of their
ancestral territory.

I would like to thank my children: Fox and Hazel, and my loving partner Megan
for their support and patience in allowing me the time and space to continue
working on this thesis even when it went on much longer than I had originally
anticipated and meant the sacrifice of some of our precious shared weekend time.
I'm deeply grateful for their willingness to prioritize my personal development
and their confidence in my eventual success.

